version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/users:/mosquitto/config/users
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ${DATA_DIR}/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:7.2.2
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana
    restart: always

  mqttbridge:
    image: avaldebe/pypms
    container_name: mqttbridge
    depends_on:
      - mosquitto
      - influxdb
    build: .
    command: ["pms", "bridge",
        "--mqtt-topic", "aqmon/+/+/+",
        "--mqtt-host", "mosquitto",
        "--mqtt-user", "mqttuser",
        "--mqtt-pass", "mqttpassword",
        "--db-host", "influxdb",
        "--db-user", "root",
        "--db-pass", "root",
        "--db-name", "home_db"
    ]
    restart: always

  mqttpypms:
    image: avaldebe/pypms
    container_name: mqttpypms
    depends_on:
      - mosquitto
      - mqttbridge
    build: .
    command: ["pms",
        "--sensor-model", "PMSx003",
        "--serial-port", "/dev/ttyUSB0",
        "--interval", "60",
        "mqtt",
        "--topic", "aqmon/h501-livingroom",
        "--mqtt-host", "mosquitto",
        "--mqtt-user", "mqttuser",
        "--mqtt-pass", "mqttpassword"
    ]
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
